### ISSUE TITLE
Initialize Paroller on an element

### ISSUE THREAD

**Issue by shahroq** [tgomilar/paroller.js#10]
Hi,
I want to use this plugin for a targeted  element like this:
`$(".my-element").paroller({ factor: '0.5', type: 'foreground', direction: 'horizontal' });`
As long as i send options via jQuery options, i suppose it doesn't need any data-paroller-* attributes, but the parallax effect does not working when i remove all data-paroller-* attributes.

**Comment by tgomilar** [comment]
Check out latest release: [https://github.com/tgomilar/paroller.js/releases/tag/v1.3.0](url)
