### ISSUE TITLE
background images not keeping height on page scroll

### ISSUE THREAD

**Issue by jough74** [tgomilar/paroller.js#11]
On your [demo site](https://tgomilar.github.io/paroller.js/) you have 2 examples of vertical parallax, one with "hello parallax" in the heading and one below it with "scrolling is fun".   On your site, as on mine, the "scrolling is fun" example does not maintain the height of the background image as you scroll the page up and down. The top example maintains a height of 316px regardless of page scroll (at least on large screens). The lower one shrinks from 316px to about 237px in height when it is near the bottom of the pageview. 

Inspecting your site I dont see any difference in the css between these 2 examples. The only difference is the data-paroller-factor (.5 and -.15 respectively) and the image sizes.  On my site no matter what data-paroller-factor I use or image size, the background images do not maintain their height throughout page scroll, even with adding a min-height rule with !important. 

I am trying to achieve what you have in your top example ("hello parallax") (a fixed height throughout) but instead getting what you have in the example below it ("scrolling is fun").  Any suggestions? Thank you

**Comment by tgomilar** [comment]
@jough74 data-paroller-factor should do the trick but it depends on image and div container size/height. If  data-paroller-factor doesn't help try using `background-repeat: repeat` to achieve background parallax effect 😉
