### ISSUE TITLE
Can't make it work with Angular

### ISSUE THREAD

**Issue by strikkerpt** [tgomilar/paroller.js#20]
Hello! I'm trying to add paroller into a angular project...

I'm calling $(window).parallax(); and have some elements with data attributes inside a ng-view but it seems is not working properly, nothing moves as aspected.

I also tried to call the elements via javascript but got the same result.

I don't know if I'm missing something here... Thank you for your time!

**Comment by tgomilar** [comment]
Try latest release [https://github.com/tgomilar/paroller.js/releases/tag/v1.3.0](url) 
Have in mind that paroller.js is jQuery plugin.
