### ISSUE TITLE
Example is broken in Chrome

### ISSUE THREAD

**Issue by fjeddy** [tgomilar/paroller.js#22]
Title says it all, all images in your given example are 100% static and doesn't move an inch in the latest version of Chrome for MacOS.

**Comment by depositado** [comment]
+1

**Comment by geri777** [comment]
+1

**Comment by carasmo** [comment]
+1

**Comment by carasmo** [comment]
Chrome and FireFox MacOS broken examples

**Comment by Uranbold** [comment]
+1

**Comment by tgomilar** [comment]
Fixed 😉
