### ISSUE TITLE
New standalone fork

### ISSUE THREAD

**Issue by ange007** [tgomilar/paroller.js#24]
Hello.
I made an independent fork for my personal needs: https://github.com/ange007/paroller.js-modern

Since the code is heavily rewritten then the usual PR seems to me not appropriate.
If the work done is of interest, you can transfer the code here.

Changes from the original:
- **AMD** and **CommonJS** init support
- New plugin structure _(class/prototype)_
- Recalculation when resizing a window
- `reinit` and `destroy` functions
- Removed code duplication
- Other...

**Comment by toddpadwick** [comment]
@ange007 is there a usage reference? 
It doesn't seem to work in the same way.

**Comment by ange007** [comment]
@toddpadwick 
At the moment, no, because it was used only for themselves.

**Comment by corymckenzie** [comment]
so instead of being able to help ghost with his problem you just made it worse
