### ISSUE TITLE
Destroy and re-initiate on window resize

### ISSUE THREAD

**Issue by functionandform** [tgomilar/paroller.js#25]
Great plugin, very easy to use however I am having an issue where the values end up being wrong when the window is re-sized. This is due to the size of containers and objects changing due to media query breakpoints. 
So I need to re-calculate the transforms on window resize. Is there a destroy/re-calc function?

**Comment by ange007** [comment]
Hello. 
Look at https://github.com/tgomilar/paroller.js/issues/24

**Comment by toddpadwick** [comment]
Excellent, cheers @ange007 :)

**Comment by fjeddy** [comment]
@ange007 I get that the author of this library is AFK or have given it up, but advertising your own library in issues + making your own issue is just bad practice and poor judgement.

**Comment by ange007** [comment]
@fjeddy , I just shared my experience. And since the project was barely alive, I decided that the author might want to transfer my work in the new version.

**Comment by fjeddy** [comment]
@ange007 Right, "Shared my experience" is absolutely not what you're doing here. But regardless, i'm not here to argue, what to do with you is up to the author, I just wanted to throw in my two cents on how despicable it is.

Don't forget, there are tons of these libraries out there, most of them way better then yours.

**Comment by toddpadwick** [comment]
To be honest @fjeddy , as this repository seems pretty much dead I found @ange007 's response nothing but helpful. 'Despicable' seems a little dramatic. If you are not here to help solve the issue I posted, then why are you here if not 'to argue'?

**Comment by fjeddy** [comment]
@toddpadwick Of course you find it helpful, which is why it's despicable, hijacking someone elses project isn't cool, regardless of it's status.

**Comment by michaelCaleyWhaley** [comment]
@fjeddy the whole point of having public repositories is so people can share and enhance projects. If we all thought like you every project would start from scratch.

**Comment by fjeddy** [comment]
@michaelCaleyWhaley If this was a fork, I would agree, but as he mentions himself, it's pretty much a rewrite (And not a very good one), and hence, it has nothing to do in this repo.

**Comment by ange007** [comment]
@fjeddy, You have a very strange argument. I do not ascribe to myself the original code. In the version that is in my repository, links are brought here.

Yes, I did fork not using GitHub, but only because I rewrote part of the component for myself. And in the record with information about the fork - I suggested to the author to transfer the code to this repository if to him.

**Comment by tgomilar** [comment]
Hi,
every developer has It's own views on how to contribute or not to open source. Personally I don't mind my code to be copied or rewritten after all paroller.js is an opensource project and anyone can use It. Also It is good to (try to) understand what is the best practice to contribute to opensource projects and what flow of forking and merging is most commonly used 😉 .

Anyhow this feature is added in latest release: [V1.4.0](https://github.com/tgomilar/paroller.js/releases/tag/v1.4.0).
I hope it helps 😉.
