### ISSUE TITLE
How to use without bootstrap

### ISSUE THREAD

**Issue by macha1011** [tgomilar/paroller.js#29]
Hey ! 

I'm trying to put paroller on my html, but it doesn't work. 
I was wondering if it's because I don't use the bootstrap grid ?
For now, I position my elements (in % ) out of the screen and I would like to make them enter horizontally when the user scrolls. 
Do you have any idea of how I should proceed ? 
Thanks in advance

**Comment by tgomilar** [comment]
Hey,
any errors in Console? Do you have jQuery and paroller.js scripts included? Did you initialise paroller.js ` $("[data-paroller-factor]").paroller();`? Otherwise paste your code and I will look into it 😉  

Not using Bootstrap shouldn't be the reason for paroller.js to stop working.

**Comment by macha1011** [comment]
No there's no errors in console, I included all the script as written in you demo page.
Jquery is included and paroller also! They are both in my data files.

Here's my code ! 
/////


<div id="scrollablecontent">
				
				<div style="width:50px;height:500px;background-color:grey;"></div>

				<div  data-paroller-factor="-0.3"
					  data-paroller-type="foreground"
					  data-paroller-direction="horizontal"
					  id="img1">
						<img src="img/1.png">
				</div>
				
				<div style="width:50px;height:500px;background-color:grey;"></div>
				
				<div data-paroller-factor="0.1"
					 data-paroller-type="foreground"
					 data-paroller-direction="horizontal"
					 id="img2">
					<img src="img/2.jpg">
				</div>
				
				<div style="width:50px;height:500px;background-color:grey;"></div>

</div>
			
			<script src="script/jquery-3.3.1.min.js"></script>
			<script src="script/jquery.paroller.js"></script>
			<script src="script/jquery.paroller.min.js"></script>
			<script>
				$(function () {
					$('[data-paroller-factor]').paroller();
				});
			</script>
		
		</body>

/////

Thank you so much ! :))

**Comment by tgomilar** [comment]
I created Codepen where you can see that paroller.js is working with your html/css code: [Testing paroller.js](https://codepen.io/anon/pen/LQaZER)

Make sure that you have the latest paroller.js version: [paroller.js/releases](https://github.com/tgomilar/paroller.js/releases) 😉 
So far I don't see any other possible bugs.
