### ISSUE TITLE
adding easing

### ISSUE THREAD

**Issue by jough74** [tgomilar/paroller.js#3]
I would like to add easing to my parallax animations, but don't know enough about data attributes to know how to do that with your plugin.  For example, I am adding a horizontal parallax effect to heading tags, which is cool, but would be even cooler with some subtle easing added. 
Thanks for considering it.

**Comment by tgomilar** [comment]
You can add easing effect on any element ignoring the paroller.js plugin functionality.
If you want to add easing effect with jQuery check out this example: [https://jqueryui.com/easing/](url) or maybe find some useful plugin like this one: [http://gsgd.co.uk/sandbox/jquery/easing/](url)
You can also use CSS [transition/transition-timing-function](https://www.w3schools.com/css/css3_transitions.asp) or even combine CCS and JS to achieve effect: [http://easings.net](url)

I don't know which easing effect you have in mind so I can't give you concrete code example.

**Comment by jough74** [comment]
Gotcha. That makes perfect sense. I dont know why I thought the scrolling and easing had to be coming from the same plugin, but of course you're right. Sorry for the dumb question but thanks for the reply.
