### ISSUE TITLE
get scrolltop from other element

### ISSUE THREAD

**Issue by fabiovaz** [tgomilar/paroller.js#31]
i have some issues to use paroller with other scripts like smooth-scrollbar ( https://github.com/idiotWu/smooth-scrollbar )
via smoothscroll i can pick the distance of top (
https://github.com/idiotWu/smooth-scrollbar/blob/574026fed21559d30d334b413b069c3ea2e0ca69/docs/api.md#scrollbarscrolltop )

but how can i pass that information to paroller?

**Comment by tgomilar** [comment]
Hi, paroller.js calculates current vertical position with .scrollTop()
method when [resize ](https://github.com/tgomilar/paroller.js/blob/master/dist/jquery.paroller.js#L149)and/or [scroll ](https://github.com/tgomilar/paroller.js/blob/master/dist/jquery.paroller.js#L186)event happens.
You cannot pass .scrollTop() to paroller.js. You can only pass [this ](https://github.com/tgomilar/paroller.js/blob/master/dist/jquery.paroller.js#L104) values.
