### ISSUE TITLE
Show your work

### ISSUE THREAD

**Issue by tgomilar** [tgomilar/paroller.js#32]

**Comment by tgomilar** [comment]
🔗 [Alveus](https://alveus.si/en) 
🔗 [Alveus history](https://alveus.si/en/company-history)
A web-shop page where proller.js is used on front page and some subpages with exposed content/images.

**Comment by MattGreyDesign** [comment]
@tgomilar The parallax seems buggy for me, there seems to be a delay on the movement and elements float upward beyond their bounds. I just wanted to let you know.

**Comment by tgomilar** [comment]
Thanks for your feedback @MattGreyDesign 
Do you maybe have more info about the browsers you were testing site in? Maybe some feedback on screen widths or breakpoints  where parallax behaved buggy?

**Comment by elliottmangham** [comment]
@tgomilar Whitetail Gin uses it extensively, and beautifully, on many pages! https://whitetailgin.com
