### ISSUE TITLE
Making paroller stop scrolling when reached an area

### ISSUE THREAD

**Issue by hemademedoit** [tgomilar/paroller.js#36]
I'm trying to use this with a site, inside a div the text scrolls but keeps scrolling if you scroll past it, I would like to have it stop when the page reaches an area, and start again once the user scrolls back up.

So basically reach a Y position stop scrolling, then when scroll back up past the Y position to add the effect again.

**Comment by tgomilar** [comment]
Hi, paroller.js does not support this functionality. 
You can still write some JS code where you check Y position and change CSS properties transform and background position when element reaches a certain vertical position. That way you can rewrite values that were added to elements with paroller.js.

Unless you provide some Codepen example I can't help you with your specific case.
