### ISSUE TITLE
missing h1 tag after adding paroller.js

### ISSUE THREAD

**Issue by kevindank** [tgomilar/paroller.js#37]
Hello,  I added paroller to http://dev2.heliosipm.com/services/systems-and-data.html  and im now experiencing an issue where my H1 tag is hidden unless i adjust the window size.  This isn't a responsive or media query issue, once i drag the window back to original size the text displays, making it smaller or larger doesn't make it dissapear...its only on load that im required to change screensize in either direction before my h1 tag will display.

**Comment by tgomilar** [comment]
Hello, I'm not sure if I understand your problem? It seems like H1 is shown on all resolutions...
