### ISSUE TITLE
Alignment issue on Firefox when applying CSS filters

### ISSUE THREAD

**Issue by ADavidLiu** [tgomilar/paroller.js#38]
I'm not sure if this is a Firefox bug or a plugin issue. Line 22 of CSS in this codepen is the problem: https://codepen.io/ADavidLiu-1478715687/pen/xaXLBK

Does anyone know how to fix this or an alternative to apply the filter? I've tried applying it to the parent container but the result is the same, leading me to think it is a bug in Firefox and not paroller. Thanks.

**Comment by tgomilar** [comment]
This looks like CSS/Firefox bug
