### ISSUE TITLE
Height issue when image repeat is no-repeat

### ISSUE THREAD

**Issue by ramesh-inc** [tgomilar/paroller.js#39]
I am new to parallax effect and you are the first library that I chose to work with.I want a parallax effect to a background-image but it's not taking the viewport height. As you have mentioned in your demos in your documentation, I followed ,

**html**
`class="jumbotron" style="background: url('https://unsplash.it/1920/800?image=950') no-repeat center;
background-size: cover;"
data-paroller-factor="0.5"
data-paroller-factor-xs="0.2"`

**js**
`$('.jumbotron').paroller();`

But this is only working when I have `background-repeat:repeat`. When I have `no-repeat` it scroll the half of the page and my inner content going to the white section where the `background-image` is not visible. Help me to solve this.

**Comment by tgomilar** [comment]
@ramesh-inc that is how parallax effect works on backgrounds.
Maybe you should try:
- using lower paroller-factor 
- using paroller on `<img>` element (data-paroller-type="foreground") instead on `<div>` with background (data-paroller-type="background")
