### ISSUE TITLE
alter data attribute with media queries?

### ISSUE THREAD

**Issue by jough74** [tgomilar/paroller.js#4]
Can you suggest a way to have a different data-paroller-factor on smaller screens than on desktop? I am using paroller to add parallax to text, and on smaller screens this creates issues. I'd like a desktop data-paroller-factor of -0.35 but on mobile either 0 or closer to 0. Not sure how  to do this. 
Thanks for any ideas you can suggest!

**Comment by tgomilar** [comment]
So far this functionality is not implemented in paroller.js. 
I will find a solution and upgrade plugin (hopefully very soon 😉).
In the meantime you can try scaling elements or using smaller font-size on certain breakpoint via CSS `@media (max-width: 768px) {} `query maybe even add some padding/margin so the text will be still visible on smaller resolutions.

**Comment by jough74** [comment]
Wow I am very impressed that you'd add this functionality just for my asking, though I'm sure it will be helpful to others as well. I look forward to the upgrade. Thanks for the "responsiveness" of your support for this already fantastic plugin.

**Comment by jough74** [comment]
Hello, just following up on this thread to ask if this enhancement is still
in the works?
thank you

-
​jh
​

**Comment by tgomilar** [comment]
Hi,
so far this solution is not published on Githib yet... but hopefully will be soon. I just want to add some other functionalities to Paroller and than published an update ;)

**Comment by Ceyar** [comment]
This would be a great features.

Nice plugin by the way.

**Comment by cohsteve** [comment]
Hello, any update on this feature?
Are there any plans to add more control over start/end position of parallax items?

**Comment by ADavidLiu** [comment]
I'm also interested on this feature being added

**Comment by tgomilar** [comment]
Hi,
this feature is added in latest release: [V1.4.0](https://github.com/tgomilar/paroller.js/releases/tag/v1.4.0).
I hope it helps 😉.
