### ISSUE TITLE
Default Setup not working?

### ISSUE THREAD

**Issue by ThisGuyHasTwoThumbs** [tgomilar/paroller.js#43]
Hey,

I have set up my div like this:

```
<div class="col-sm-12" id="some-div" data-paroller-factor="0.3" data-paroller-type="foreground" data-paroller-direction="horizontal">
        <div class="row">
            <div class="div-container col-sm-6">
                <img src="<?php echo plugins_url('module/images/'). 'placeholder.jpeg'; ?>" class="img-responsive" />
                <p>TAGLINE</p>
            </div>
        </div>

        <div class="row">
            <div class="div-container col-sm-6 col-sm-offset-6">
                <p>ANOTHER TAGLINE</p>
                <img src="<?php echo plugins_url('module/images/'). 'placeholder.jpeg'; ?>" class="img-resposnive" />
            </div>
        </div>

        <div class="row">
            <div class="div-container col-sm-6">
                <h3>YET ANOTHER TAGLINE</h3>
                <img src="<?php echo plugins_url('module/images/'). 'placeholder.jpeg'; ?>" class="img-responsive" />
            </div>
        </div>
    </div>
```

And my jQuery:

```
    //parallax scroll
    $('#some-div').paroller();

    $('.div-container').paroller({
        factor: 0.5,
        factorXs: 0.2,
        type: 'foreground',
        direction: 'horizontal'
    })
```

my console outputs:

> TypeError: $(...).paroller is not a function

What am I doing wrong?

I've checked my <body> element and can see the <script> for paroller before my main.js file for my module and well after jQuery include.

Followed steps on website for basic usage (will play with later .. when it works)

**Comment by tgomilar** [comment]
It looks like paroller.js isn't included correctly (check if you have the [latest version](https://cdn.jsdelivr.net/npm/paroller.js@1.4.4/dist/jquery.paroller.min.js) of paroller ) to your project or isn't included at all.

**Comment by ThisGuyHasTwoThumbs** [comment]
@tgomilar I replaced file with linked version - seems ok - downloaded from site so maybe you'd like to update the download file? :)

**Comment by tgomilar** [comment]
@ThisGuyHasTwoThumbs the files are identical 😉
