### ISSUE TITLE
Hero section problem

### ISSUE THREAD

**Issue by premitheme** [tgomilar/paroller.js#44]
Great plugin, however, I have a little issue and all my tries to solve it went with the wind.

I have a fullscreen hero section with a line of text centered vertically and horizontally, and I want the text to have vertical parallax animation on scroll.

The problem is when I apply paroller on the text (using data attributes) it's not centered anymore when page scroll = 0. It has a little bit of initial translate transform up or down depending on the direction I set. I can understand this is useful when applying paroller on an element in the middle of the page, but when it applied to an element in the first section (like hero section in my case) this initial transform will break the layout. The text element should be in its original place, then it moves slowly on scroll.

I tried to play with the calculations in the code but had no luck. If someone can give an advice I will appreciate it.

Regards

**Comment by tgomilar** [comment]
@premitheme 
This look more a bug than a feature, I agree. 
Will take a look and try to fix it in another release.

In the mean time try setting the translate: transform value via CSS with opposite value/direction that paroller.js does. Take a look at this [Codepen example](https://codepen.io/tgomilar/pen/BGyjoZ) (h1 comments).

**Comment by premitheme** [comment]
Thanks, again great plugin and super easy to use.

**Comment by tgomilar** [comment]
@premitheme should be fixed in latest paroller.js [version 1.4.5 ](https://github.com/tgomilar/paroller.js/releases/tag/v1.4.5) 😉

**Comment by elliott-impression** [comment]
@tgomilar seems as though the issue has came back in 1.4.6? Even on your [forked] example it jumps https://codepen.io/elliottmangham/pen/dLBMPq
