### ISSUE TITLE
Stopping the transition from going negative

### ISSUE THREAD

**Issue by vergedesign** [tgomilar/paroller.js#45]
hello. This isn't an issue, sorry for posting here.. rather its a question..

Is there any way to stop the plugin once the element has reached its initial place?

I have two squares, initially starting off (without paroller), they are positioned exactly on top of each other (one is absolutely positioned on top of the other)

Now I've set a horizontal paroller direction on one of them, with a factor of 1.

What I want is to stop any more transition once it reaches its original position, so I want to stop translateX(0) and not let it go negative. 

I hope that makes sense, thanks in advance and once again apologies for posting here. Is there a better place to post questions?

**Comment by vergedesign** [comment]
oh and thank you very much for this amazing plugin. Its a real game changer for dynamic websites. It makes me want to go back and redo every site ive ever made!

**Comment by tgomilar** [comment]
@vergedesign please prepare Codepen example if this is still an issue.
