### ISSUE TITLE
Vertical Scrolling Position On Mobile Snaps Wrong

### ISSUE THREAD

**Issue by nicdunn** [tgomilar/paroller.js#46]
Hi there,

I've found an issue where if you scroll to the top of the page then the bottom whilst using a mobile - safari iphone. The vertical position is offset wrong until you scroll in the opposite direction again then it jumps back to the correct position? 

Notice in the image below. The Text has gone over the line. If I then scroll up on my phone it pings back to the correct position instantly.

Any help in fixing this would be amazing. As I absolutely love this plugin! 

![img_0834](https://user-images.githubusercontent.com/44873897/48210266-e1dc0280-e36e-11e8-9d47-8308be57cf62.PNG)

**Comment by tgomilar** [comment]
@nicdunn should be fixed in latest release-v1.4.5
