### ISSUE TITLE
Using Paroller on elements at the top of the page

### ISSUE THREAD

**Issue by elliott-impression** [tgomilar/paroller.js#48]
Hi!

I am hoping to have an element positioned at the top of the page (a Hero Banner) and I want to implement paroller so that its' content parallaxes.

At the moment it seems on page-load paroller kicks in and applies the transform despite not started scrolling yet. For example `transform: translateY(-84px);`, which causes an unwanted gap.

How is it possible to have transform initiate at 0 or null so that it is only applied when the user starts scrolling.

Thank you and great job

**Comment by elliott-impression** [comment]
Bump @tgomilar?

**Comment by tgomilar** [comment]
@elliott-impression please look at [this issue](https://github.com/tgomilar/paroller.js/issues/44).

**Comment by elliott-impression** [comment]
Super, thanks!
