### ISSUE TITLE
Temperamental scroll position

### ISSUE THREAD

**Issue by elliottmangham** [tgomilar/paroller.js#49]
Hello,

Firstly, thanks for an awesome library!

I've found a recurring issue which breaks the layout of a page. All I can guess is that the paroller elements are scrolling too early/late. 

You can see the example here: https://goo.gl/qEbFSN

Sometimes when you load the page, the paroller elements scroll into the correct position, however, other times, they're completely wrong.

It's worth noting that the issue seems to be more severe on elements further down the page, and the higher elements are not affected as much.

See screenshots from the link above as an example:

**Broken:**
![screenshot 2019-01-15 at 13 03 04](https://user-images.githubusercontent.com/12933804/51182556-7fe7ce00-18c6-11e9-8a3e-152a7c87b175.png)

**Working:**
![screenshot 2019-01-15 at 13 02 59](https://user-images.githubusercontent.com/12933804/51182557-7fe7ce00-18c6-11e9-8b0b-c8fe7dd892aa.png)

This seems to be the case even in the latest browsers, however, I've tested on all browsers, like Chrome 60 - 70, Edge, IE, Firefox and Safari.

I am hoping to find a solution and cause of the issue so I can both fix this and prevent it from happening again.

I would really appreciate some help on this and I am grateful for your time.

Thank you

**Comment by tgomilar** [comment]
@elliottmangham is this still an issue? I've tested it and couldn't reproduce mentioned bug. Please try latest paroller.js [version v1.4.5](https://github.com/tgomilar/paroller.js/releases/tag/v1.4.5) and let me know if the problem still occurs.
