### ISSUE TITLE
question for creating a widget with paroller

### ISSUE THREAD

**Issue by michellomp** [tgomilar/paroller.js#5]
Hi I try to create a widget with paroller for [elementor](https://github.com/pojome/elementor) and it works great in the frontend but it doesn't work in preview. It doesn't give me any error but there's no parallax effect. I guess the problem comes from their way to base it on [$scope variable](https://github.com/pojome/elementor-hello-world/blob/master/assets/js/hello-world.js). My code is this one
```
( function( $ ) {
	var WidgetHelloWorldHandler = function( $scope, $ ) {
		
		$scope.find('.background-paroller').paroller({ factor: '-0.2'}); 
		
		
	};
	
	// Make sure you run this code under Elementor..
	$( window ).on( 'elementor/frontend/init', function() {
		elementorFrontend.hooks.addAction( 'frontend/element_ready/parallax.default', WidgetHelloWorldHandler );
	} );


	
} )( jQuery );
```
for 
```
<div class="jumbotron background-paroller text-center bg-faded my-5"
             style="background: url(<?php  echo $image[url];  ?>) no-repeat center;"
             data-paroller-factor="-0.2">
            <h1 class="heading-1 py-5 text-white">Hello Parallax!</h1>
            <p class="text-white">data-paroller-factor="-0.2"</p>
        </div>
			
```
Do you have any idea of what can block this ?
Thanks

**Comment by tgomilar** [comment]
Hmm, I don't know Elementor. Maybe ask for help them ;).
It looks like paroller.js is not initialized in preview mode - you need to figure out how to run paroller JS in preview mode...
