### ISSUE TITLE
Elements shift down only when at top of page

### ISSUE THREAD

**Issue by abaney** [tgomilar/paroller.js#50]
If I reload / visit a page and I'm at the very top, the elements that have Paroller applied to them are positioned where they're intended to be, however, when I start to scroll, they jump down from where they're intended to be, but the parallax effect works fine.

However, if I scroll down the page just a little bit from the top, and reload the page, the elements are positioned lower than where they're intended to be. As I start to scroll, they don't jump down, they just work as the parallax effect.

Any idea what's going on? Maybe Paroller isn't being initiated at the load of a new page?

Thanks in advance for your help!

**Comment by elliottmangham** [comment]
@abaney I may have misunderstood, but please have a look at #44 for paroller elements that at the top of the page.

**Comment by abaney** [comment]
@elliottmangham Thanks for your reply! This helped, however, if I resize the window, then start to scroll again, the elements jump down the page a bit. The parallax effect is still working at that point, though. This same thing happens in the Code Pen example from the Issue [#44](https://github.com/tgomilar/paroller.js/issues/44) page.

**Comment by tgomilar** [comment]
@abaney @elliottmangham  should be fixed in latest paroller.js [version 1.4.5 ](https://github.com/tgomilar/paroller.js/releases/tag/v1.4.5) 😉

**Comment by elliottmangham** [comment]
@tgomilar nice fix!

**Comment by oueryemchi** [comment]
I am using 1.4.6 and the moment you scroll down it jumps a distance vertically (depends on the factor), but it always jumps to that distance then as you scroll down more it starts parallaxing..
