### ISSUE TITLE
Elements with background scroll snap once after refresh

### ISSUE THREAD

**Issue by urban07** [tgomilar/paroller.js#51]
Hi, I'm having some trouble with the plugin.
It does work, I had no problem initiating it etc., however, when I scroll down to a paroller-initiated element (I only use vertically scrolled backgrounds in my project btw) and then refresh the page, the background-position value is wrong at first. It does change to a correct one, right after I scroll the page either up or down, but it happens in a snap and it just looks terrible :(

It's really weird, because I even copied the example from the plugin website and imported the same jquery and plugin versions to check it, and it still snapped after refresh.

Here's a screenshot of background-position before and after scrolling the page down about 80px after refresh:
![image](https://user-images.githubusercontent.com/45875885/51620058-e2c60e80-1f31-11e9-866f-dc06f2dd8a76.png)

**Comment by urban07** [comment]
So... it's working fine today ._.

I don't know what was the problem. Maybe some of my js code was interfering with paroller.js, or there was some bug in chrome when I was working on it yesterday...
Whatever the case was, it's all good now :)

**Comment by Mohitgold** [comment]
When you did hard refresh i think , you see this issue again.... go to middle of page and do hard refresh wihout scroll `Ctrl+F5`.

**Comment by Mohitgold** [comment]
Use this:
  setTimeout(function() {
    $('[data-paroller-factor]').paroller({
      type: 'foreground',
      factor: 0.2
    });
  }, 100);

    setTimeout(function() {
      $("html,body").scrollTop(2);
    }, 200);
