### ISSUE TITLE
Jump on scroll vertically

### ISSUE THREAD

**Issue by oueryemchi** [tgomilar/paroller.js#53]
Lovely plugin! I have a simple 2 full width containers with backgrounds, I set up the parallax vertically on the second container (which is below the first one.), the moment you start scrolling, the 2d container jumps down a distance before it starts smoothly parallax. is it a bug? thanks

I am using the latest version 1.4.6.

**Comment by abvas** [comment]
I have the same issue. Jumps in both horizontal and vertical. Jumps at the very beginning, as soon as I start to scroll. I am using the latest version 1.4.6. too.

**Comment by tgomilar** [comment]
@oueryemchi @oueryemchi please provide code example and info like which browser and OS do you use.

**Comment by abvas** [comment]
Here is an example. A piece of code.

<div id="element-id3" style="top: 20px; width: 1423px; left: 0px; position: absolute; box-sizing: border-box; z-index: 7; height: 378px; border-radius: 0px; background: url(&quot;https://d1muf25xaso8hp.cloudfront.net/https%3A%2F%2Fs3.amazonaws.com%2Fappforest_uf%2Ff1549104144278x215452887107377760%2FOpatija_Croatia_Houses_Roads_Street_Night_Street_528036_2560x1440.jpg?w=2048&amp;h=544&amp;auto=compress&amp;fit=crop&quot;) 0px center no-repeat; background-size: cover;">	
</div>

<div id="element-id4" style="top: 400px; width: 1423px; left: 0px; position: absolute; box-sizing: border-box; z-index: 7; height: 378px; border-radius: 0px; background: url(&quot;https://d1muf25xaso8hp.cloudfront.net/https%3A%2F%2Fs3.amazonaws.com%2Fappforest_uf%2Ff1549104144278x215452887107377760%2FOpatija_Croatia_Houses_Roads_Street_Night_Street_528036_2560x1440.jpg?w=2048&amp;h=544&amp;auto=compress&amp;fit=crop&quot;) 0px center no-repeat; background-size: cover;">	
</div>


<script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous"></script>

<script src="jquery.paroller.min.js"></script>

<script>
    $(document)
        .ready(function () {
			$(`#element-id3`).paroller({
                        factor: 0.5,            // multiplier for scrolling speed and offset
                        type: 'background',     // background, foreground
                        direction: 'horizontal', // vertical, horizontal
                        transition: 'transform 0.2s ease-in', // CSS transition
			});
			$(`#element-id4`).paroller({
                        factor: 0.5,            // multiplier for scrolling speed and offset
                        type: 'background',     // background, foreground
                        direction: 'vertical', // vertical, horizontal
                        transition: 'transform 0.2s ease-in', // CSS transition
			});           
        });
</script>


Used Firefox and Chrome.
As soon as I start to scroll - a jump occurs. And then it works well. I like the plugin very much. But this race at first spoils everything. Tell me what I'm doing wrong.

**Comment by tgomilar** [comment]
@abvas please use [Codepen](https://codepen.io/) for code examples. Your code is unreadable and can not be tested instantly.

**Comment by abvas** [comment]
https://codepen.io/abvas/pen/mvwyab
This is my piece of code. I really like the plugin, but this race at the very beginning of the scrolling spoil everything. Tell me what I'm doing wrong.

**Comment by illiterati** [comment]
@tgomilar I think the problem only occurs when the element to be affected is already in the viewport on page load. Initial positions should probably be set before scrolling, to avoid the jump on scroll.

**Comment by abvas** [comment]
It's clear. And the element when loading the page can be hidden out of sight. But I wanted the element to be visible immediately after the page loads. But if it is visible, then at the beginning of the scroll is visible and racing. That is why the question arises what to do.

**Comment by illiterati** [comment]
As a hacky workaround, I changed line 135 from
   var factor = 0;
to
   var factor = setMovement.factor($this, width, options);

and I also commented out the factor = 0; at line 197.

**Comment by abvas** [comment]
Unfortunately, at the very beginning, the race remained. And then it works fine.

**Comment by illiterati** [comment]
Sorry, I also set the initial background position with CSS. Unfortunately, my hack only helps elements near the top of the document, it messes up ones further down.

**Comment by rom1unik** [comment]
Hi ... same issue, the hack of [illiterati] is good for the returning to the top, but onload and on resize don't work ... plz this plugin is so cool ... the world NEED IT

**Comment by Mohitgold** [comment]
Best solution, my issue fixed:
Use latest file of js for "jquery.paroller.min.js"
download and replace this:
https://github.com/tgomilar/paroller.js/releases/tag/v1.4.6

**Comment by abvas** [comment]
@Mohitgold,
Did not help. It still jumps at the very beginning of the scroll.
[https://codepen.io/abvas/pen/mvwyab](url)

**Comment by Mohitgold** [comment]
Use this:
setTimeout(function() {
$('[data-paroller-factor]').paroller({
type: 'foreground',
factor: 0.2
});
}, 100);

```
setTimeout(function() {
  $("html,body").scrollTop(2);
}, 200);
```

**Comment by abvas** [comment]
@Mohitgold,
Did not help.

**Comment by Fyrins** [comment]
Nice Plugin ! 
But i've the same problem with this initial jump on vertical - foreground element :-/ When I scroll a little, my div immediately jump (translate) to 40px in the "factor" direction. This is a really strange behavior.

**Comment by computerarts** [comment]
@Mohitgold 
although the "solution" can somewhat hide the problem when the page loads, if the user decides to scroll back up to the top, the jump is still visible.

**Comment by oueryemchi** [comment]
> @oueryemchi @oueryemchi please provide code example and info like which browser and OS do you use.

on Windows.. basic setup no params, had to find another solution. good luck guys!

**Comment by emha** [comment]
It seems that the current version 1.4.6 broke something. The working version is 1.4.4. So change your package.json like this:

`"paroller.js": "^1.4.6"`
to
`"paroller.js": "1.4.4"`

After you changed your package.json and before your make your `npm install` do these steps:
1. Remove the existing package with `npm uninstall paroller.js`
2. Remove your `package-lock.json`.

After these steps do your `npm install`. You can check your installed version of paroller.js with `npm list paroller.js`. It should now be `1.4.4` and work.

**Comment by abvas** [comment]
@emha
And where can I get version 1.4.4?

**Comment by emha** [comment]
> @emha
> And where can I get version 1.4.4?
> I have jumps on version 1.4.1.

You just have to change you **package.json**. If you don't use **npm/yarn** you have to go back to `1.4.1`. You can find this release here:
[https://github.com/tgomilar/paroller.js/releases/tag/1.4.1](url)

**Comment by srevenant** [comment]
This is a small PR that fixes the jump for me: https://github.com/tgomilar/paroller.js/pull/62

And this is a PR that includes this, plus a lot of var cleanup: https://github.com/tgomilar/paroller.js/pull/63

I haven't tested all of the use cases to see if this break anything else.

**Comment by manikbajaj** [comment]
> 1. npm uninstall paroller.js

Actually, Version "1.4.4" does not have this problem. Reverted back temporarily to solve the issue and waiting until a solution is released. @srevenant already pointed out on the PR, this breaks the background parallax needs to be tested before merging.

**Comment by pixluser** [comment]
I was having this problem in 2020 also… using the 1.4.1 fixed my problems, thanks @emha  !
