### ISSUE TITLE
Use a delay?

### ISSUE THREAD

**Issue by laurend** [tgomilar/paroller.js#54]
I'm getting a weird issue with inconsistent placement of the parallax background on a fairly long-scrolling page with a bunch of high-res images in the foreground. It often corrects itself when I refresh the page. I'm thinking it could be a delay issue, as if the images are taking too long to load in some cases and paroller pulls incorrect dimensions. Is there an easy way to have Paroller load a bit later, after all of the items on the page have had a chance to load? Or does it do this already?

**Comment by Mohitgold** [comment]
Use this:
  setTimeout(function() {
    $('[data-paroller-factor]').paroller({
      type: 'foreground',
      factor: 0.2
    });
  }, 100);

    setTimeout(function() {
      $("html,body").scrollTop(2);
    }, 200);

**Comment by Mohitgold** [comment]
Another solution which is best:
Use latest file of js for "jquery.paroller.min.js" 
download and replace this:
https://github.com/tgomilar/paroller.js/releases/tag/v1.4.6
