### ISSUE TITLE
Recalculate paroller.js after isotope grid

### ISSUE THREAD

**Issue by simopetrelli** [tgomilar/paroller.js#56]
Hi Tgomilar,
In my page, I have a dynamic height element (grid isotope) that does not allow the paroller.js element to calculate the right position well.

Is there a recalculation method after loading isotope? are there any other solutions you would recommend to me?

Thanks a lot

**Comment by tgomilar** [comment]
I can only help if code expamle is provided. I don't use "grid isotope".
