### ISSUE TITLE
enhancement question

### ISSUE THREAD

**Issue by soniapello** [tgomilar/paroller.js#6]
Hi thanks for your great plugin
but I wonder if you consider adding option for center parallax elements in the viewport like [this ](https://github.com/dixonandmoe/rellax#centering)?

**Comment by tgomilar** [comment]
Hi,
interesting idea. Will take a look at it ;). Right now I'm preparing an update of paroller.js and maybe this functionality will also be added to an update - will let you know ;)

**Comment by tgomilar** [comment]
So far this is not implemented in [new version](https://github.com/tgomilar/paroller.js/releases/tag/v1.4.0) of paroller.js. 
If anyone is interesting in developing this functionality fell free to fork project and merge request your changes 😉
