### ISSUE TITLE
Destroy paroller

### ISSUE THREAD

**Issue by Margaret0106** [tgomilar/paroller.js#7]
Hello! How can I destroy paroller? For example, on small devices I don't need it.

**Comment by tgomilar** [comment]
All paroller.js does is set one of these options:

- **transform:  translateY()** on element moving in vertical direction when data-paroller-type="foreground" is set - `style="transform: translateY(y);"`
- **transform:  translateX()** on element moving in horizontal direction when data-paroller-type="foreground" is set - ``style="transform: translateX(x);"``
- different **background position** for background parallax effect in vertical direction
`background: url("/your/path") center Y no-repeat;`
- different **background position** for background parallax effect in horizontal direction
`background: url("/your/path") X center no-repeat;`

If you want to stop paroller.js effect for certain breakpoint let say for max-width: 768px you can do it via CSS like this:

-  for data-paroller-type="foreground"
` @media (max-width: 768px) {
   .my-paroller-element {
     transform: none !important;
 }
} `
- for background parallax effect
` @media (max-width: 768px) {
   .my-paroller-element {
     background-position: center center !important;
 }
} `
