### ISSUE TITLE
Type: 'background' not working

### ISSUE THREAD

**Issue by glo-www** [tgomilar/paroller.js#70]
hi,

with version 1.4.6, background parallax is not working (cf you website)
ok with 1.4.4

https://tgomilar.github.io/paroller.js/#demo

cheers,

**Comment by mikhailrepka** [comment]
not working for me too

**Comment by tgomilar** [comment]
Version 1.4.6 had this bug, please use version 1.4.7

**Comment by amuhr-design** [comment]
Please update the jquery.paroller.min file in version 1.4.7. 
It still contains the 1.4.6. code,
Cheers

**Comment by SorinSu** [comment]
still not working 1.4.7
