### ISSUE TITLE
Smoother initialization

### ISSUE THREAD

**Issue by inovek** [tgomilar/paroller.js#8]
I don't really like how it looks when my page loads with Paroller for parallax background-containers.

Did I something wrong?

**My CSS:**
```
.parollerFrame {
    width: 100%;
    background-repeat: no-repeat;
    background-position: center center;
    background-size: cover;
    overflow: hidden;
    min-height: 400px;
}
```

My issue is that Paroller belongs with white-gaps in background in State 2, until the first scroll event accurs. (see text and image)

> **State 1: No Paroller (Good)**
> Your own HTML and CSS loads, all looks fine.
> 
> **State 2: Paroller initialization (Ugly)**
> Paroller was executed and the positions of the backgrounds become really strange. And nothing changes, until State 3.
> 
> **Stage 3: Paroller in Action (Nice)**
> Only after the first wheel-event, Paroller does his job fine and moves the images to the correct positions.

**How could I solve this, so that the visitor doesn't see the parollerFrames staying in state 2?**

___

![states](https://user-images.githubusercontent.com/1033171/27856683-1be42ef4-616f-11e7-8483-24335019ab0f.png)

**Comment by tgomilar** [comment]
Hey,
great explanation of the problem @inovek :wink:
First solution that comes to my mind is:

**HTML**
```
<body class="preload"></div>
```
**JS**
```
$("#content").paroller();
$(window).load(function() {
    setTimeout(function () {
        $("body").removeClass("preload");
    }, 1100);
});
```
**CSS**
```
.preload [data-paroller-factor] {
   transition: 1s;
}
```
For better understanding check out this GIF -  it starts on page reload.
![example-resize](https://user-images.githubusercontent.com/21154699/27879696-beb3a2a6-61c2-11e7-93b6-fa64b19c7838.gif)
I hope the code is self-explenatory 😉 .

**Comment by tgomilar** [comment]
Another easier solution should be calling/initializing paroller() inside $(document).ready() function.

```
$( document ).ready(function() {
      $("#layout-content").paroller();
});
```
@inovek please give feedback if this solves your problem 😉.
